// ==============================================================================
// DB_Mechs - Масиви механізмів
// ==============================================================================
// Project  : Elevator_System v1.0.0
// Generated: 2026-02-26 16:22:16
// Source   : graph.json
// Devices  : 4 / 4
// ==============================================================================

DATA_BLOCK "DB_Mechs"
{ S7_Optimized_Access := 'TRUE' }
VERSION : 1.0

VAR
    Mechs  : ARRAY [0.."MECHS_COUNT"]   OF "UDT_BaseMechanism";
    Redler : ARRAY [0.."REDLERS_COUNT"] OF "UDT_Redler";
    Noria  : ARRAY [0.."NORIAS_COUNT"] OF "UDT_Noria";
    Gate2P : ARRAY [0.."GATES2P_COUNT"] OF "UDT_Gate2P";
    Fan    : ARRAY [0.."FANS_COUNT"] OF "UDT_Fan";
END_VAR

BEGIN
    // === ІНІЦІАЛІЗАЦІЯ СЛОТІВ ===

    // --- Redler (slot ) ---
    Mechs[0].SlotId     := 0;
    Mechs[0].DeviceType := "TYPE_NORIA";
    Mechs[0].TypedIndex := 0;
    Mechs[0].Enable_OK  := TRUE;

    // --- Redler (slot ) ---
    Mechs[1].SlotId     := 1;
    Mechs[1].DeviceType := "TYPE_NORIA";
    Mechs[1].TypedIndex := 1;
    Mechs[1].Enable_OK  := TRUE;

       // --- Redler (slot ) ---
    Mechs[2].SlotId     := 2;
    Mechs[2].DeviceType := "TYPE_NORIA";
    Mechs[2].TypedIndex := 2;
    Mechs[2].Enable_OK  := TRUE;


    Mechs[3].SlotId     := 3;
    Mechs[3].DeviceType := "TYPE_GATE2P";
    Mechs[3].TypedIndex := 0;
    Mechs[3].Enable_OK  := TRUE;

END_DATA_BLOCK
